### ISSUE TITLE
Client crashes

### ISSUE THREAD

**Issue by ivoronin** [ao-data/albiondata-client#13] opened 2023-01-27 05:38 UTC
Getting constant client crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x454bc3b]

goroutine 1180 [running]:
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).uploadWithPow(0xc0000b32e0, 0x0, 0x0, 0x0, 0x0, 0xc0000adab0, 0x10, 0xc0000161e0, 0xed, 0xf0, ...)
        /usr/src/app/client/uploader_http_pow.go:81 +0x33b
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).sendToIngest(0xc0000b32e0, 0xc0000161e0, 0xed, 0xf0, 0x47729e3, 0x13)
        /usr/src/app/client/uploader_http_pow.go:134 +0x111
github.com/broderickhyman/albiondata-client/client.sendMsgToUploaders(0xc0000161e0, 0xed, 0xf0, 0x47729e3, 0x13, 0xc0001b2a20, 0x1, 0x1)
        /usr/src/app/client/dispatcher.go:116 +0xae
github.com/broderickhyman/albiondata-client/client.sendMsgToPublicUploaders(0x46a51c0, 0xc0006e4aa0, 0x47729e3, 0x13, 0xc0001bf200)
        /usr/src/app/client/dispatcher.go:68 +0x1e9
github.com/broderickhyman/albiondata-client/client.operationAuctionGetOffersResponse.Process(0xc0004380b0, 0x1, 0x1, 0xc0001bf200)
        /usr/src/app/client/operation_auction_get_offers.go:58 +0x392
created by github.com/broderickhyman/albiondata-client/client.(*Router).run
        /usr/src/app/client/router.go:52 +0x2d5
```

Last messages from the debug log:
```
DEBU[2023-01-27T10:25:31+05:00] Got response to AuctionGetOffers operation... 
INFO[2023-01-27T10:25:31+05:00] Sending 18 market requests to ingest         
DEBU[2023-01-27T10:25:31+05:00] GETTING POW                                  
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2196826 1:[3 -13 82 112 -24 38 0 -37 8 -89 -27 -53 -63 107 -23 55 66 34 102 102 52 65 90 -75 -85 -63 -4 -68 70 66]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2197741 1:[3 -29 73 107 -24 38 0 -37 8 113 -12 93 -63 112 -109 20 66 -19 -102 -103 65 65 0 -14 -116 -63 -60 88 50 66]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2197714 1:[3 -29 -116 75 -24 38 0 -37 8 66 -35 45 -63 -17 -63 -69 65 -89 -52 -52 56 65 -36 36 -121 -63 34 97 -102 65]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: [10]evActiveSpellEffectsUpdate - map[0:2185660 1:[695 969 311 371 514 431] 2:[100 184.92752 243.11807 243.11807 100 243.11807] 3:[100 146.82451 174.19029 174.19029 100 174.19029] 4:[66649249 67154428 67369245 67388382 59898185 67389213] 5:[1 1 3 4 1 4] 7:[75 18 36 73 -110 36 73 -110 36 73 -110 36 1] 8:[17208836] 9:[17] 10:[0 0] 252:10] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: [20]evCastHits - map[0:2185660 1:2185660 2:431 3:1 4:0 252:20] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2194099 1:[3 67 22 113 -24 38 0 -37 8 37 112 -64 -63 -83 105 47 66 26 0 0 26 65 -25 -72 -94 -63 -45 54 67 66]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2197587 1:[3 83 8 101 -24 38 0 -37 8 18 -39 -87 -63 -44 -1 105 63 -56 0 0 4 65 -23 -22 -81 -63 24 -49 -121 63]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: [13]evCastStart - map[0:2164282 1:67389171 4:67389971 5:2920 6:-101 7:2164282 8:92 9:13 252:13] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2197637 1:[3 -29 -100 114 -24 38 0 -37 8 55 18 60 -62 -109 89 -15 65 -100 0 0 -80 64 -79 33 62 -62 104 81 -20 65]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2197584 1:[3 67 -121 115 -24 38 0 -37 8 63 -42 73 -63 62 21 68 66 -45 0 0 -80 64 -55 103 -116 -63 32 71 78 66]] 
DEBU[2023-01-27T10:25:31+05:00] EventDataType: ERROR - map[0:2192861 1:[3 -45 87 119 -24 38 0 -37 8 -118 -56 -109 -63 -46 82 52 66 -98 -102 -103 21 65 -68 -82 -33 -63 76 -60 9 66]] 
```

```
% uname -a
Darwin macbook.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```

**Comment by kochd** [comment] 2023-01-27 14:24
How often does this happen when you say constant?
I've seen this in rare occasions but failed to reproduce it willingly.

**Comment by phendryx** [comment] 2023-01-27 14:27
Also, note it's running on a M1/M2 Mac. It's possible it could be a emulation thing since the binary is not targeted for ARM.

**Comment by ivoronin** [comment] 2023-01-28 06:48
Well it happens every few hours.
No idea what leads to the crash yet.

**Comment by kochd** [comment] 2023-01-28 08:33
I suspect your internet connection to be unstable? Or can you rule that out?

https://github.com/ao-data/albiondata-client/blob/40dead766ecc2be22cb01d27ca3a12a7161336b6/client/uploader_http_pow.go#L81

This would happen if resp.Body was nil (e.g. no response from server)
The error handling can be improved here

**Comment by ivoronin** [comment] 2023-01-28 10:44
> I suspect your internet connection to be unstable? Or can you rule that out?
> 
> https://github.com/ao-data/albiondata-client/blob/40dead766ecc2be22cb01d27ca3a12a7161336b6/client/uploader_http_pow.go#L81
> 
> This would happen if resp.Body was nil (e.g. no response from server) The error handling can be improved here

Thats definitely could be the case, my internet connection is flaky

**Comment by toxicon** [comment] 2023-02-19 14:32
INFO[2023-02-19T17:27:56+03:00] Sending 50 market requests to ingest         
ERRO[2023-02-19T17:27:56+03:00] Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow": read tcp 192.168.1.2:58772->138.197.64.234:4223: read: connection reset by peer 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x81b98a]

goroutine 25 [running]:
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).uploadWithPow(0xc00000e810, 0x0, 0x0, 0x0, 0x0, 0xc00034a4f0, 0x10, 0xc000293500, 0x301b, 0x3500, ...)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:81 +0x34a
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).sendToIngest(0xc00000e810, 0xc000293500, 0x301b, 0x3500, 0x93a36a, 0x13)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:134 +0x111
github.com/broderickhyman/albiondata-client/client.sendMsgToUploaders(0xc000293500, 0x301b, 0x3500, 0x93a36a, 0x13, 0xc00017ea30, 0x1, 0x1)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:116 +0xb4
github.com/broderickhyman/albiondata-client/client.sendMsgToPublicUploaders(0x8a2360, 0xc0000e66c0, 0x93a36a, 0x13, 0xc00018f200)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:68 +0x1e8
github.com/broderickhyman/albiondata-client/client.operationAuctionGetRequestsResponse.Process(0xc000179880, 0x32, 0x32, 0xc00018f200)
        /home/runner/work/albiondata-client/albiondata-client/client/operation_auction_get_requests.go:44 +0x3a5
created by github.com/broderickhyman/albiondata-client/client.(*Router).run
        /home/runner/work/albiondata-client/albiondata-client/client/router.go:52 +0x2a5

**Comment by toxicon** [comment] 2023-02-19 14:37
Agan crash
INFO[2023-02-19T17:34:20+03:00] Starting Albion Data Client, version: 0.1.23 
INFO[2023-02-19T17:34:20+03:00] This is a third-party application and is in no way affiliated with Sandbox Interactive or Albion Online. 
INFO[2023-02-19T17:34:20+03:00] Additional parameters can listed by calling this file with the -h parameter. 
INFO[2023-02-19T17:34:20+03:00] Watching Albion                              
INFO[2023-02-19T17:35:52+03:00] Updating player location to @ISLAND@ec5aa555-e889-4f19-8eb4-576e81c643e5. 
INFO[2023-02-19T17:35:52+03:00] Updating player ID to 4edb1b3e-0f2b-4341-b4ad-eb90dd59910d. 
INFO[2023-02-19T17:35:52+03:00] Updating player to Umabaka.                  
INFO[2023-02-19T17:36:12+03:00] Updating player location to 4000.            
INFO[2023-02-19T17:36:13+03:00] Updating player location to 4000.            
INFO[2023-02-19T17:36:28+03:00] Updating player location to 4002.            
INFO[2023-02-19T17:36:33+03:00] Sending 50 market requests to ingest         
ERRO[2023-02-19T17:36:34+03:00] Error in Pow Get request: Get "http://www.albion-online-data.com:4223/pow": read tcp 192.168.1.2:35308->138.197.64.234:4223: read: connection reset by peer 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x81b98a]

goroutine 28 [running]:
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).uploadWithPow(0xc00000e810, 0x0, 0x0, 0x0, 0x0, 0xc00033b7e0, 0x10, 0xc0003b7500, 0x312e, 0x3500, ...)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:81 +0x34a
github.com/broderickhyman/albiondata-client/client.(*httpUploaderPow).sendToIngest(0xc00000e810, 0xc0003b7500, 0x312e, 0x3500, 0x93a36a, 0x13)
        /home/runner/work/albiondata-client/albiondata-client/client/uploader_http_pow.go:134 +0x111
github.com/broderickhyman/albiondata-client/client.sendMsgToUploaders(0xc0003b7500, 0x312e, 0x3500, 0x93a36a, 0x13, 0xc00017ea30, 0x1, 0x1)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:116 +0xb4
github.com/broderickhyman/albiondata-client/client.sendMsgToPublicUploaders(0x8a2360, 0xc0003788b8, 0x93a36a, 0x13, 0xc00018f200)
        /home/runner/work/albiondata-client/albiondata-client/client/dispatcher.go:68 +0x1e8
github.com/broderickhyman/albiondata-client/client.operationAuctionGetRequestsResponse.Process(0xc000179c00, 0x32, 0x32, 0xc00018f200)
        /home/runner/work/albiondata-client/albiondata-client/client/operation_auction_get_requests.go:44 +0x3a5
created by github.com/broderickhyman/albiondata-client/client.(*Router).run
        /home/runner/work/albiondata-client/albiondata-client/client/router.go:52 +0x2a5

**Comment by phendryx** [comment] 2023-02-19 14:39
What happens if you goto http://www.albion-online-data.com:4223/pow in a web browser?

**Comment by toxicon** [comment] 2023-02-19 14:41
![изображение](https://user-images.githubusercontent.com/6388838/219955182-e119fa25-e72c-42bc-a452-2baf56c03d7f.png)
Omg Blocked?

**Comment by phendryx** [comment] 2023-02-19 14:43
Sounds like it. Not by us, but by your ISP/country/etc. I forget exactly where it was, but Russia apparently blocked a bunch of Digital Ocean IP ranges. You can try a full connection VPN that reroutes ALL traffic (TCP/UDP and all ports). Someone was successful with TOR, but I don't know the details of how they got it to work.

**Comment by toxicon** [comment] 2023-02-19 14:46
WTF
Working with DE vpn. Dunno. Roskomnadzor block domain or ip

**Comment by phendryx** [comment] 2023-02-19 14:52
Are you able to goto https://www.albion-online-data.com/ successfully?

**Comment by phendryx** [comment] 2023-02-19 15:03
Try `albiondata-client.exe -i http+pow://pow.albion-online-data.com` and see if the issue goes away.

**Comment by toxicon** [comment] 2023-02-19 15:09
Reboot router and working, sorry

**Comment by phendryx** [comment] 2023-02-19 15:10
Ah yes, the old "Microsoft Fix".. reboot and see if it works. Well, glad your issue is sorted. Others have had this same issue with no resolve yet.

Going to close this since you're working properly now.

**Closed by phendryx** 2023-02-19 15:10 UTC
